### ISSUE TITLE
build-and-push.sh script in health-checks is no longer executable

### ISSUE THREAD

**Issue by TechnoRoss** [docker-training/ddev-labs#21]
The script will not run unless you chmod +x... This was not the case before, so I am assuming recent tweaks lost that bit.

**Comment by katieannemills** [comment]
Where are you running this? `bash build-and-push.sh` works for me on a VM spun up by `train`.

**Comment by TechnoRoss** [comment]
lab guide for 9.1.2.2:

$ export MY_DOCKER_ID=<Docker ID>
$ ./build-and-push.sh

If your solution is correct, then that needs updating to read
$ bash build-and-push.sh

**Comment by katieannemills** [comment]
thanks, @TechnoRoss! fixed per your suggestion in PR above.
