### ISSUE TITLE
MongoDB code is included although it's asked to be added in the exercises

### ISSUE THREAD

**Issue by houbena** [docker-training/ddev-labs#23]
Exercises api-tests.md

The mongodb part shouldn't be included in the initial git repo.
e.g. in main.py
`import PyMongo`
`app.config['MONGO_HOST'] = 'mongo'
etc.

The code must be cleaned to correspond to the instructions.

**Comment by katieannemills** [comment]
I think this got resolved in #22, please reopen if I've misunderstood.
