### ISSUE TITLE
Copy pasting from pdf

### ISSUE THREAD

**Issue by martencassel** [docker-training/ddev-labs#25]
When i copy/paste snippets from the pdf into text files sometimes newlines are not added.

In the developer exercises at 4.1 Back-end Development. Copy pasting the api/Dockerfile.api file will generate a maven error for me because the COPY . . command is added to the RUN mvn line.

**Comment by katieannemills** [comment]
Yes, the PDFs are frustrating like this - have you seen the HTML versions of the exercises? See the setup command corresponding to the version of the slides you are teaching here: https://github.com/docker-training/presentations/releases. Find the release you're teaching, and grab the command under 'Corresponding Exercises'.

**Comment by martencassel** [comment]
@BillMills thanx.
